# Welcome to Jekyll!

# Website settings
title: Piyush Mehta
description: Piyush's Website, used Jekyll and github pages.
keywords: PiyushMehta,Piyush,Mycollegeforums,Jekyll,github,gh-pages
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://piyushmehta.com  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Piyush Mehta  # Be used at blog posts' author.
  first_name: Piyush  # Be used at index page about me section.
  last_name: Mehta  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: piyush97  # Leave blank if you don't have now
  linkedin_id: piyush24 # Leave blank if you don't have now
  facebook_username: pyushh  # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: me@piyushmehta.com  # Leave blank if you don't have now
  cv: http://cv.piyushmehta.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-github
    - name: fa-linux
  skill_icon2:
    - name: icon-shell
    - name: fa-apple
  desc: I am an Engineering Student and I have a keen interest in software development.I spend most of my time converting ideas into code.I enjoy learning new languages and skills from online courses.Besides work, I love to capture the sweetest moments of my life in 16:9 camera roll.
  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: Piyush Mehta

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off  # index page carousel switch
blog_carousel: off  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

